### PR TITLE
CAN Timeout Watchdog (with WWDT)

### PR DESCRIPTION
**Pull request by eufrizz**
The watchdog sets the control mode back to idle when no CAN messages are received for a configurable amount of time. Enabled/disabled and timeout set via a CAN endpoint on 0x2A with the set_watchdog command.

Reimplemented with WWDT (as asked for here: https://github.com/tinymovr/Tinymovr/pull/195)

### CODE REVIEW

**Comment by yconst** [comment]
Looks good! I'm going to add a unit test for this and merge it. Thanks for the contribution!

**Comment by yconst** [comment]
I've added license headers to the files you contributed, please check if ok, then we can merge

**Comment by eufrizz** [comment]
Added an extra check to cap the timeout to the maximum allowed by uint16 if a higher/invalid value is requested. Worth checking in the unit test? Happy to merge if you are.

**Comment by yconst** [comment]
> Added an extra check to cap the timeout to the maximum allowed by uint16 if a higher/invalid value is requested. Worth checking in the unit test? Happy to merge if you are.

We'd need a getter endpoint for that. I think we're good enough, I re-ran the tests, and they are passing. I think we can merge.

**Pull request merged**
