### PR TITLE
Hall mode update

### PR DESCRIPTION
**Pull request by eufrizz**
- A new hall sensor calibration, which increments the motor angle and discovers each sector. Works more reliably than the previous method in my experience.
- Some extra functions for reading/writing to an maXXX encoder to write/read registers.
- Tweaks to the CAN endpoints.
  - I've decided to just replace the last hall sector mapping with the current hall angle, which is more useful for debugging. We can't have both because each CAN packet is 8 bytes as far as I can see. The hall sensor UVW is never 000 or 111 so the first and last sectors are never used anyway. Alternatively, instead of sending a byte for each sector, we could send 4 bits (3 bits for the hall sector and 1 buffer bit to make it fit nicely into a byte) and update the unpacking on the Python side. I decided not to do this as I noticed you were rewriting the comms layer anyway.

### CODE REVIEW

**Comment by yconst** [comment]
Thanks for this! Will review in the weekend.

**Comment by yconst** [comment]
I did some minor changes, all looks good, but I'll test this in the coming days since atm I don't have access to a hall sensored motor.

**Comment by eufrizz** [comment]
Looks good, thanks for reviewing! It works fine on my hardware.

**Comment by yconst** [comment]
Merging this as it works fine on my hw as well!

**Pull request merged**
